<a href="https://colab.research.google.com/github/dhanarajappu456/tensor_flow_familiarize/blob/main/dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# dataframe

In [19]:
#numpy arary to dataframe

import numpy as np
import pandas as pd
array_=np.array([[1,2,3],[4,5,6]])
data_fr=pd.DataFrame(array_)
print("array to dataframe\n",data_fr)


#numpy arary to dataframe

array_1=np.array(data_fr)
print("\ndataframe to array\n",array_1)

#dataframe using dictionay 

dict_={'name':["Dhanaraj","Radhika","George","Amala"],'age':[21,"21",21,21]}
data_fr2=pd.DataFrame(dict_)
print(data_fr2)

array to dataframe
    0  1  2
0  1  2  3
1  4  5  6

dataframe to array
 [[1 2 3]
 [4 5 6]]
       name age
0  Dhanaraj  21
1   Radhika  21
2    George  21
3     Amala  21


# dateranges

In [29]:
month_=pd.date_range(19980714,periods=6,freq='D')
print(month_)

DatetimeIndex(['1970-01-01 00:00:00.019980714',
               '1970-01-02 00:00:00.019980714',
               '1970-01-03 00:00:00.019980714',
               '1970-01-04 00:00:00.019980714',
               '1970-01-05 00:00:00.019980714',
               '1970-01-06 00:00:00.019980714'],
              dtype='datetime64[ns]', freq='D')


# head and tail function

In [45]:
#generate randonm numbers of order (6,4)

random=np.random.randn(6,4)
print("\n",random,"\n")
#data frame generation using random numbers
data_fr3=df=pd.DataFrame(random,index=month_,columns=list('VWXY'))
print(data_fr3)

data_fr3.head(3)
print("____________________________________")


#selecting single colmn

data_fr3['Y']

#selecting multple_columns
 
data_fr3[['V','Y']]

#dropcolumns

dropped=data_fr3.drop(columns=['V','Y'])
print("\ndrop col ______________\n")
print(dropped)





 [[ 1.36582929 -0.44855533  0.23026322 -2.6576794 ]
 [-0.87649928 -0.01027286  2.06679109 -0.1284036 ]
 [-0.65193549  1.13679706  0.7171671  -0.46765701]
 [-0.10174079 -1.55855074 -0.86775112  0.01019966]
 [-1.23754236 -0.84809572  0.73121956  0.35149337]
 [ 0.58888931 -0.3262508   0.45117173 -0.10496041]] 

                                      V         W         X         Y
1970-01-01 00:00:00.019980714  1.365829 -0.448555  0.230263 -2.657679
1970-01-02 00:00:00.019980714 -0.876499 -0.010273  2.066791 -0.128404
1970-01-03 00:00:00.019980714 -0.651935  1.136797  0.717167 -0.467657
1970-01-04 00:00:00.019980714 -0.101741 -1.558551 -0.867751  0.010200
1970-01-05 00:00:00.019980714 -1.237542 -0.848096  0.731220  0.351493
1970-01-06 00:00:00.019980714  0.588889 -0.326251  0.451172 -0.104960
____________________________________

drop col ______________

                                      W         X
1970-01-01 00:00:00.019980714 -0.448555  0.230263
1970-01-02 00:00:00.019980714 -0.010

# concatenate two datfranme

In [50]:

df1 = pd.DataFrame({'name': ['John', 'Smith','Paul'],
'Age': ['25', '30', '50']},
index=[0, 1, 2])
df2 = pd.DataFrame({'name': ['Adam', 'Smith' ],
'Age': ['26', '11']},
index=[3, 4])
concated_=pd.concat([df1,df2])
print(concated_)


    name Age
0   John  25
1  Smith  30
2   Paul  50
3   Adam  26
4  Smith  11


# manage duplicate rows 

In [51]:
filtered_dupli_=concated_.drop_duplicates('name') # smith is duplicated twice ,so remove
print(filtered_dupli_)

    name Age
0   John  25
1  Smith  30
2   Paul  50
3   Adam  26
